default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

production:
  <<: *default
  database: myapp_production

development:
  <<: *default
  database: myapp_development
  host: db

test:
  <<: *default
  database: myapp_test
  host: db
  